version: '3'

services:
  # Serviço de frontend
  angular:
    container_name: angular
    build: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - node
      - mongo
      - mongo-express
  
  # Serviço de backend
  node:
    container_name: node
    build: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    env_file:
      - .env
    depends_on:
      - mongo

  # Serviço de banco de dados
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
          
  # Serviço admin do banco de dados
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo/
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}
    depends_on:
      - mongo

  
  # grafana:
  #  image: grafana/grafana-enterprise
  #  container_name: grafana
  #  restart: unless-stopped
  #  ports:
  #  - '8080:8080'
  #  networks:
  #    - MasterStock
  #  volumes:
  #    - .:/usr/app  
